### ISSUE TITLE
[Suggestion] Don't count pregnant animals.

### ISSUE THREAD

**Issue by frenchiveruti** [FluffierThanThou/MedicalTab#22]
So, I have a bunch of animals that are for fighting, and then the breeding animals, that are most of the time pregnant, when I go into a fight. The animals get hurt of course, but pregnant animals show on the "filter" for medical issues because they have "a moving eff. penalty" due to pregnancy.
Can you make a filter filter? So pregnant animals aren't counted.
Thanks

**Comment by FluffierThanThou** [comment]
I've had a look at this, but it's not really possible to separate pregnant animals from otherwise hurt animals. I could filter out all pregnant animals, but that would also affect animals that are hurt AND pregnant.

**Comment by frenchiveruti** [comment]
What about a thing that checks for injuries except for pregnancy, so if it's pregnant it forgets it but if it's pregnant and has another injury it does count? I'm asking because I don't know if you fixed this really :)
